version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${CATALOGDB_SA_PASSWORD}
    ports:
      - "${CATALOGDB_PORT}:1433"
    volumes:
      - mssql_catalog:/var/opt/mssql

  distributedcache:
    container_name: distributed-cache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  catalog.api:
    container_name: catalog-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${CATALOG_API_URL}
      ConnectionStrings__Products: ${CONN_CATALOG_DB}
    depends_on:
      - catalogdb
      - distributedcache
    ports:
      - "${CATALOG_API_PORT}:80"
      - "${CATALOG_API_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  shoppingCartdb:
    container_name: shopping-cart-db
    environment:
      POSTGRES_USER: ${SHOPPINGCARTDB_USER}
      POSTGRES_PASSWORD: ${SHOPPINGCARTDB_PASSWORD}
      POSTGRES_DB: ${SHOPPINGCARTDB_NAME}
    restart: always
    ports:
      - "${SHOPPINGCARTDB_PORT}:${SHOPPINGCARTDB_PORT}"
    volumes:
      - postgres_shoppingcart:/var/lib/postgresql

  shoppingCart.api:
    container_name: shopping-cart-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${SHOPPINGCART_API_URL}
      ApiSettings__GatewayAddress: ${API_GATEWAY_ADDRESS}
      ConnectionStrings__Database: ${CONN_SHOPPINGCART_DB}
      ConnectionStrings__SqlDatabase: ${CONN_CATALOG_DB}
      ConnectionStrings__Redis: ${CONN_REDIS}
      MessageBroker__Host: ${RABBITMQ_HOST}
      MessageBroker__UserName: ${RABBITMQ_USER}
      MessageBroker__Password: ${RABBITMQ_PASSWORD}
    depends_on:
      - shoppingCartdb
      - catalogdb
      - distributedcache
      - messagebroker
    ports:
      - "${SHOPPINGCART_API_PORT}:80"
      - "${SHOPPINGCART_API_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  ordering.api:
    container_name: ordering-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ORDERING_API_URL}
      ConnectionStrings__Database: ${CONN_ORDER_DB}
      MessageBroker__Host: ${RABBITMQ_HOST}
      MessageBroker__UserName: ${RABBITMQ_USER}
      MessageBroker__Password: ${RABBITMQ_PASSWORD}
      FeatureManagement__OrderFullfilment: ${FEATURE_ORDER_FULLFILMENT}
    depends_on:
      - orderdb
      - messagebroker
    ports:
      - "${ORDERING_API_PORT}:80"
      - "${ORDERING_API_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  orderdb:
    container_name: orderdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${ORDERDB_SA_PASSWORD}
    restart: always
    ports:
      - "${ORDERDB_PORT}:1433"
    volumes:
      - mssql_order:/var/opt/mssql

  apigateway:
    container_name: api-gateway
    environment:
      ASPNETCORE_URLS: ${API_GATEWAY_URL}
      ReverseProxy__Clusters__catalog-cluster__Destinations__destination1__Address: ${REVERSE_PROXY_CATALOG_ADDRESS}
      ReverseProxy__Clusters__shoppingCart-cluster__Destinations__destination1__Address: ${REVERSE_PROXY_SHOPPINGCART_ADDRESS}
      ReverseProxy__Clusters__ordering-cluster__Destinations__destination1__Address: ${REVERSE_PROXY_ORDERING_ADDRESS}
      ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address: ${REVERSE_PROXY_AUTH_ADDRESS}
    depends_on:
      - catalog.api
      - shoppingCart.api
      - auth.api
    ports:
      - "${API_GATEWAY_PORT}:80"
      - "${API_GATEWAY_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

  identitydb:
    container_name: identitydb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${IDENTITYDB_SA_PASSWORD}
    restart: always
    ports:
      - "${IDENTITYDB_PORT}:1433"

  auth.api:
    container_name: auth-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${AUTH_API_URL}
      ConnectionStrings__Database: ${CONN_IDENTITY_DB}
    depends_on:
      - identitydb
      - distributedcache
    ports:
      - "${AUTH_API_PORT}:80"
      - "${AUTH_API_HTTPS_PORT}:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro

volumes:
  mssql_catalog:
  postgres_shoppingcart:
  mssql_order: