version: '3.4'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  shoppingCartdb:
    image: postgres
    
  shoppingCart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart/ShoppingCart.API/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile

  orderdb:
    image: mcr.microsoft.com/mssql/server

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile

volumes:
  mssql_catalog:
  postgres_shoppingcart:
 