version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyPass123"
    ports:
      - "1434:1433"
    volumes:
      - mssql_catalog:/var/opt/mssql

  # distributedcache:
  #   container_name: distributed-cache
  #   restart: always
  #   ports:
  #     - "6379:6379" 

  catalog.api:
    container_name: catalog-api
    environment:
     # ASPNETCORE_ENVIRONMENT: Development
     ASPNETCORE_URLS: "http://+:80"
     ConnectionStrings__Products: "Server=catalogdb;Database=CoffeeShop_Catalog;User=sa;Password=MyPass123;Encrypt=False;TrustServerCertificate=True"
    depends_on:
      - catalogdb
     # - distributedcache
    ports:
      - "7000:80"
      - "7070:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
     # - ./Services/ShoppingCart/ShoppingCart.API/Security/Certificates:/usr/local/share/ca-certificates/

  shoppingCartdb:
    container_name: shopping-cart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ShoppingCartDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_shoppingcart:/var/lib/postgresql/data/

  shoppingCart.api:
    container_name: shopping-cart-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ApiSettings__GatewayAddress: "http://api-gateway:80"
      ConnectionStrings__Database: "Host=shoppingCartdb;Port=5432;Database=ShoppingCartDb;Username=postgres;Password=postgres"
      ConnectionStrings__SqlDatabase: "Server=catalogdb;Database=CoffeeShop_Catalog;User=sa;Password=MyPass123;Encrypt=False;TrustServerCertificate=True"
      # ConnectionStrings__Redis: "distributedcache:6379"
      # MessageBroker__Host: rabbitmq://ecommerce-mq:5672
      # MessageBroker__UserName: guest
      # MessageBroker__Password: guest
    depends_on:
      - shoppingCartdb
      - catalogdb 
     # - distributedcache
     # - messagebroker
    ports:
      - "7001:80"
      - "7071:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
      #- ./ApiGateway/ApiGateway/Security/Certificates:/usr/local/share/ca-certificates

  # messagebroker:
  #   container_name: messagebroker
  #   hostname: ecommerce-mq
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  ordering.api:
    container_name: ordering-api
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: "http://+:80"
        ConnectionStrings__Database: Server=orderdb;Database=CoffeeShop_Order;User Id=sa;Password=MyPass123;Encrypt=False;TrustServerCertificate=True
        # MessageBroker__Host: rabbitmq://ecommerce-mq:5672
        # MessageBroker__UserName: guest
        # MessageBroker__Password: guest
        FeatureManagement__OrderFullfilment: false
    depends_on:
      - orderdb
     # - messagebroker
    ports:
      - "7002:80"
      - "7072:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
     # - ./Services/ShoppingCart/ShoppingCart.API/Security/Certificates:/usr/local/share/ca-certificates/

  orderdb:
    container_name: orderdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass123
    restart: always
    ports:
      - "1435:1433"
    volumes:
      - mssql_order:/var/opt/mssql

  apigateway:
    container_name: api-gateway
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ReverseProxy__Clusters__catalog-cluster__Destinations__destination1__Address: "http://catalog-api:80"
      ReverseProxy__Clusters__shoppingCart-cluster__Destinations__destination1__Address: "http://shopping-cart-api:80"
      ReverseProxy__Clusters__ordering-cluster__Destinations__destination1__Address: "http://ordering-api:80"
      ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address: "http://auth-api:80"

    depends_on:
      - catalog.api
      - shoppingCart.api
      - auth.api
    ports:
      - "7005:80"
      - "7075:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro
      #- ./ApiGateway/ApiGateway/Security/Certificates:/usr/local/share/ca-certificates
    

  identitydb:
     container_name: identitydb
     environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyPass123
     restart: always
     ports:
      - "1436:1433"
  
  auth.api:
    container_name: auth-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__Database: "Server=identitydb;Database=CoffeeShop_Identity;User Id=sa;Password=MyPass123;Encrypt=False;TrustServerCertificate=True"
    depends_on:
      - identitydb
     # - distributedcache
    ports:
      - "7007:80"
      - "7077:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/https:/https:ro 
      #- ./Services/Auth/Auth.API/Security/Certificates:/usr/local/share/ca-certificates/

volumes:
  mssql_catalog:
  postgres_shoppingcart:
  mssql_order:
